version: '2'
services:
    mskgateway-app:
        image: mskgateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mskgateway-mysql:3306/mskgateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mskgateway-mysql:
        extends:
            file: mysql.yml
            service: mskgateway-mysql
